import { GeneraFormularioReporte } from "../../components/global/GlobalForms";
import { reportFields } from "../../data/formConfig"; // Asegúrate de que este import sea correcto

const NewReport = () => {
    const initValues = {
        tipoMantenimiento: '',
        modelo: '',
        fecha: '',
        horaInicio: '',
        responsable: '',
        licencia: '',
        registro: '',
        restaurador: '',
        circuito: '',
        area: '',
        ubicacionMapa: '',
        direccion: '',
        nsRadioGabinete: '',
        potenciaSalida: '',
        rssi: -120,
        umbralRecepcion: -50,
        frecuencia: '',
        rx: '',
        tx: '',
        cablePigtail: '',
        supresor: '',
        cableLT: '',
        alturaAntena: '',
        repetidorEnlace: '',
        canalUCM: '',
        fotografiasMantto: false,
        medicionRF: false,
        medicionFuenteCD: false,
        medicionBateria: false,
        limpieza: false,
        ajusteTornilleria: false,
        cambioAntena: false,
        impermeabilizacionConectores: false,
        redireccionamientoAntena: false,
        cambioLT: false,
        cambioSupresor: false,
        cambioRadio: false,
        cambioPigtail: false,
        cambioConectores: false,
        potenciaRadio: '',
        potenciaIncidente: '',
        potenciaReflejada: '',
        vswr: '',
        voltajeAcometida: '',
        resistenciaTierra: '',
        voltajeFuente: '',
        resistenciaBateria: '',
        porcentajeBateria: '',
        anguloAzimut: '',
        placaNomenclatura: false,
        selladoGabinete: false,
        protectorAntifauna: false,
        cuchillasByPass: false,
        cuchillasLaterale: false,
        bajanteTierra: false,
        terminalPAT: false,
        apartarrayos: false,
        cableRF: false,
        calibreBajante: '',
        Observaciones: '',
        configuracionRadio: '',
        imagenEstructura: null,
        imagenGabinete: null,
        imagenRadio: null,
        imagenSupresor: null,
        imagenRestaurador: null,
        imagenTerminalTierra: null,
        imagenBajanteTierra: null,
        imagenPlaca: null,
        imagenAdicional: null,
        horaTermino: '',
    };

    const formProps = {
        data: reportFields,
        initValues,
        title: "Nuevo Reporte",
        description: "Ingrese los datos necesarios para crear un nuevo reporte",
        titleBtn: "Crear Reporte",
        msgSuccess: "Reporte creado exitosamente",
        msgError: "Error al crear el reporte",
        sendData: "InsertReporte",
    };

    return <GeneraFormularioReporte {...formProps} />;
};

export default NewReport;
