// src/modules/reports/ReportTables.jsx

import { GenerarTabla } from "../../components/global/DataTables";
import { reportHeader } from "../../data/tableHeaders";

const ReportTables = () => {
  const formProps = {
    header: reportHeader,
    title: "Listado de Reportes",
    description: "Esta tabla muestra todos los reportes disponibles.",
    titleBtn: "Agregar Reporte",
    sendData: "agregarReporte",
    data: [
      {
        id: 1,
        restaurador: "Juan Pérez",
        tipoMantenimiento: "Correctivo",
        createdBy: "Admin",
        creationDate: "2024-11-01",
        lastModified: "2024-11-10",
        actions: "Editar",
      },
      {
        id: 2,
        restaurador: "Carlos López",
        tipoMantenimiento: "Preventivo",
        createdBy: "Editor",
        creationDate: "2024-11-05",
        lastModified: "2024-11-15",
        actions: "Editar",
      },
      {
        id: 3,
        restaurador: "María Gómez",
        tipoMantenimiento: "Predictivo",
        createdBy: "Admin",
        creationDate: "2024-10-20",
        lastModified: "2024-10-25",
        actions: "Editar",
      },
      {
        id: 4,
        restaurador: "David Rodríguez",
        tipoMantenimiento: "Correctivo",
        createdBy: "RRHH",
        creationDate: "2024-09-15",
        lastModified: "2024-09-18",
        actions: "Editar",
      },
      {
        id: 5,
        restaurador: "Elena Ramírez",
        tipoMantenimiento: "Preventivo",
        createdBy: "Finanzas",
        creationDate: "2024-08-10",
        lastModified: "2024-08-12",
        actions: "Editar",
      },
      {
        id: 6,
        restaurador: "Héctor Contreras",
        tipoMantenimiento: "Predictivo",
        createdBy: "Auditor",
        creationDate: "2024-07-01",
        lastModified: "2024-07-05",
        actions: "Editar",
      },
      {
        id: 7,
        restaurador: "Gabriela Silva",
        tipoMantenimiento: "Correctivo",
        createdBy: "Marketing",
        creationDate: "2024-06-20",
        lastModified: "2024-06-22",
        actions: "Editar",
      },
      {
        id: 8,
        restaurador: "Roberto Ortega",
        tipoMantenimiento: "Preventivo",
        createdBy: "Producción",
        creationDate: "2024-05-15",
        lastModified: "2024-05-18",
        actions: "Editar",
      },
      {
        id: 9,
        restaurador: "Patricia Herrera",
        tipoMantenimiento: "Predictivo",
        createdBy: "Calidad",
        creationDate: "2024-04-10",
        lastModified: "2024-04-12",
        actions: "Editar",
      },
      {
        id: 10,
        restaurador: "Manuel Díaz",
        tipoMantenimiento: "Correctivo",
        createdBy: "Logística",
        creationDate: "2024-03-05",
        lastModified: "2024-03-07",
        actions: "Editar",
      },
      {
        id: 11,
        restaurador: "Valeria Montes",
        tipoMantenimiento: "Preventivo",
        createdBy: "Atención al Cliente",
        creationDate: "2024-02-28",
        lastModified: "2024-03-01",
        actions: "Editar",
      },
      {
        id: 12,
        restaurador: "Jorge Lara",
        tipoMantenimiento: "Predictivo",
        createdBy: "Compras",
        creationDate: "2024-02-15",
        lastModified: "2024-02-17",
        actions: "Editar",
      },
      {
        id: 13,
        restaurador: "Alicia Peña",
        tipoMantenimiento: "Correctivo",
        createdBy: "RRHH",
        creationDate: "2024-01-25",
        lastModified: "2024-01-27",
        actions: "Editar",
      },
      {
        id: 14,
        restaurador: "Fernando Torres",
        tipoMantenimiento: "Preventivo",
        createdBy: "Seguridad",
        creationDate: "2024-01-10",
        lastModified: "2024-01-12",
        actions: "Editar",
      },
      {
        id: 15,
        restaurador: "Brenda Castillo",
        tipoMantenimiento: "Predictivo",
        createdBy: "Admin",
        creationDate: "2024-12-01",
        lastModified: "2024-12-05",
        actions: "Editar",
      },
    ],
  };

  return <GenerarTabla {...formProps} />;
};

export default ReportTables;
